#!/bin/bash
echo "Configuring Options for Sonarr container."
if [ -f /config/config.xml ]; then
	echo "Config exists, editing it."
	sed -i -e 's%<Port>.*</Port>%<Port>8083</Port>%' /config/config.xml
	sed -i -e 's%<UpdateMechanism>.*</UpdateMechanism>%<UpdateMechanism>Script</UpdateMechanism>%' /config/config.xml
	sed -i -e 's%<UpdateScriptPath>.*</UpdateScriptPath>%<UpdateScriptPath>/scripts/sonarr-update.sh</UpdateScriptPath>%' /config/config.xml
else
	echo "Creating a basic config file."
	cp /config.xml /config/config.xml
fi
echo "Using following config options:"
cat /config/config.xml
